// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "b4533b27-9fa4-4a20-8544-cdfaf8987cdb");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1591334462);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1591334582);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1591334823);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1591335063);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1591334943);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1591334342);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1590951126);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1591334703);
user_pref("browser.bookmarks.editDialog.confirmationHintShowCount", 1);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 71804);
user_pref("browser.cache.disk.capacity", 655360);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1588190554);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 86);
user_pref("browser.newtabpage.activity-stream.impressionId", "{4135aaf7-deb4-461f-af43-0fcf9f950f13}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1591335433212");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1591337242212");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1591295219680");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1591298819680");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1590345470");
user_pref("browser.slowStartup.averageTime", 19144);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20190919153752");
user_pref("browser.startup.homepage_override.mstone", "69.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1590345462);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1588190570194");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.fedora.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "69.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "0ed23eec58934b2b8a10c6677f0e2ac2");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Fri, 29 May 2020 08:48:09 GMT");
user_pref("extensions.blocklist.pingCountTotal", 15);
user_pref("extensions.blocklist.pingCountVersion", 15);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1591334465);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20190919153752");
user_pref("extensions.lastAppVersion", "69.0.1");
user_pref("extensions.lastPlatformVersion", "69.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{2b825bf8-f797-481a-893a-ae0c4d655f30}\",\"addons\":{\"webcompat@mozilla.org\":{\"version\":\"6.1.0\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"fdfcbe25-73f4-4199-aba8-da5579d1cdde\",\"fxmonitor@mozilla.org\":\"fcbacb33-4f93-4682-9c76-1d11b2897ec1\",\"screenshots@mozilla.org\":\"7e288387-6cdf-45eb-a1d1-58e0a2739c7b\",\"webcompat-reporter@mozilla.org\":\"c883a464-9931-4179-a1fd-a5ee700ceff2\",\"webcompat@mozilla.org\":\"11637a1f-e48e-42ca-96ab-7e75c31752f8\",\"default-theme@mozilla.org\":\"f7b620eb-cda8-4d09-9692-9343f794057c\",\"google@search.mozilla.org\":\"c3d7600b-209c-40e7-b8fc-4c35243671e5\",\"amazondotcom@search.mozilla.org\":\"c9c1e94b-b709-4353-a427-f50b2d3d5a4f\",\"bing@search.mozilla.org\":\"e79893c0-d06e-43ad-89ea-0435756fbade\",\"ddg@search.mozilla.org\":\"248f6484-72d7-4c6e-9dd7-d7734bcc7e9c\",\"ebay@search.mozilla.org\":\"a15f416f-4a80-4028-b039-9631795725a0\",\"twitter@search.mozilla.org\":\"d61d3084-d3fb-4f12-958f-53f758ec8eeb\",\"wikipedia@search.mozilla.org\":\"daf2cc3f-6e53-49dc-9c13-139c126fd37b\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1591122489);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1588332120);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20190919153752");
user_pref("media.gmp-manager.lastCheck", 1590345497);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1591122492);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "e68c055a-c11d-4ee1-b143-b8626700c9fb");
user_pref("security.sandbox.plugin.tempDirSuffix", "9ea67f38-e4e7-469c-abaa-2557c1c4220f");
user_pref("services.blocklist.pinning.checked", 1590345846);
user_pref("services.settings.clock_skew_seconds", -1277);
user_pref("services.settings.last_etag", "\"1591315278892\"");
user_pref("services.settings.last_update_seconds", 1591335862);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1590345846);
user_pref("services.settings.main.cfr-fxa.last_check", 1590345846);
user_pref("services.settings.main.cfr.last_check", 1590345846);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1590685844);
user_pref("services.settings.main.hijack-blocklists.last_check", 1590345846);
user_pref("services.settings.main.language-dictionaries.last_check", 1590345846);
user_pref("services.settings.main.normandy-recipes.last_check", 1591334340);
user_pref("services.settings.main.sites-classification.last_check", 1590345846);
user_pref("services.settings.main.tippytop.last_check", 1590345846);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1591248832);
user_pref("services.settings.security.onecrl.checked", 1590345846);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1591122491);
user_pref("toolkit.startup.last_success", 1590345440);
user_pref("toolkit.telemetry.cachedClientID", "1f09b902-207f-44ca-92d8-d6da788415c0");
user_pref("toolkit.telemetry.previousBuildID", "20190919153752");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
